# Generated by Django 5.0.6 on 2024-05-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_mytodo_delete_homeapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytodo',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
