# Generated by Django 5.0.6 on 2024-05-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_mytodo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsonalTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('complate', models.BooleanField(default=False)),
                ('listtime', models.TimeField(auto_now_add=True)),
                ('createDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='mytodo',
        ),
    ]
