# Generated by Django 5.0.6 on 2024-05-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_parsonaltodo_delete_mytodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsonaltodo',
            name='listtime',
            field=models.TimeField(auto_now=True),
        ),
    ]
